name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        submodules: recursive

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build gcc-13 g++-13

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2.16
      with:
        key: ${{ github.job }}

    - name: Build
      env:
        CC: gcc-13
        CXX: g++-13
      run: |
        cmake -G Ninja -S hwm -B build \
        -DCCACHE_BUILD=ON \
        -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release --parallel

  ubuntu-clang-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        submodules: recursive

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build clang-18

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2.16
      with:
        key: ${{ github.job }}

    - name: Build
      env:
        CC: clang-18
        CXX: clang++-18
      run: |
        cmake -G Ninja -S hwm -B build \
        -DCCACHE_BUILD=ON \
        -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release --parallel
